name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: List files in the root directory
      run: ls -la

    - name: List files in the javier_react_github_demo directory (if exists)
      run: ls -la javier_react_github_demo

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: javier_react_github_demo

    - name: Run tests
      run: npm test
      working-directory: javier_react_github_demo

    - name: Build the project
      run: npm run build
      working-directory: javier_react_github_demo
